sonar.projectKey=smart-docs
sonar.projectName=smart-docs

sonar.sources=backend,frontend
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**

sonar.sourceEncoding=UTF-8

# Optional (if you later add tests)
sonar.tests=backend,frontend
sonar.test.inclusions=**/*.test.js,**/*.spec.js