sonar.projectKey=SmartDocs
sonar.organization=kashyapojha

sonar.projectName=SmartDocs

sonar.sources=backend,frontend
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/logs/**

sonar.sourceEncoding=UTF-8

# Optional (tests)
sonar.tests=backend,frontend
sonar.test.inclusions=**/*.test.js,**/*.spec.js